"""Terrain generator of Minecraft Alpha 1.2 – Beta 1.7.3, bit for bit.

The old games do not blend the terrain they generate with existing chunks: around a converted world
they put their own terrain right against it, with vertical walls where the heights differ.  With
the generator reproduced exactly (same seed -> same blocks) WorldBridge can write a ring of chunks
around the converted area that goes smoothly from the converted terrain to the game's own; outside
the ring the game continues seamlessly.

Only the terrain pass is reproduced (noise, biomes, surface blocks, caves: ``provideChunk``).  The
decoration (trees, ores, lakes, snow…) is left to the game: the ring chunks are written as "not
populated", exactly like a chunk the game has just generated.

Validated against 736 chunks generated by Beta 1.7.3 itself: 98.7 % of the columns identical to the
block, the rest being the game's decoration.  The quirks of the original (the 3D noise reusing the
gradients of the first y of each noise cell, the carving one block above the tested one in caves)
were checked against Modern Beta (b3spectacled, MIT licence), a faithful reimplementation.
"""

from __future__ import annotations

import math
from typing import Dict, List, Optional, Tuple

import numpy as np

MASK48 = (1 << 48) - 1
MASK64 = (1 << 64) - 1

STONE, GRASS, DIRT, BEDROCK, WATER_FLOWING, WATER, LAVA_FLOWING = 1, 2, 3, 7, 8, 9, 10
SAND, GRAVEL, SANDSTONE, ICE = 12, 13, 24, 79
SEA_LEVEL = 64


def _s64(v: int) -> int:
    v &= MASK64
    return v - (1 << 64) if v >> 63 else v


def _jdiv(a: int, b: int) -> int:
    """Java integer division (truncates towards zero)."""
    q = abs(a) // abs(b)
    return q if (a >= 0) == (b > 0) else -q


def water_in_box(blocks, x0, x1, y0, y1, z0, z1) -> bool:
    """MapGenCaves: water in the box about to be carved.  The game scans every column from y1 + 1
    down to y0 - 1 but, inside the box's outer columns, jumps from the top block straight to the
    bottom one: the outer columns are looked at whole, the inner ones at y1 + 1 and y0 - 1 only
    (both always inside the world when the scan runs: 1 <= y0, y1 <= height - 8)."""
    if x1 <= x0 or z1 <= z0 or y1 + 1 < y0 - 1:
        return False
    box = blocks[x0:x1, z0:z1, y0 - 1:y1 + 2]
    w = (box == WATER) | (box == WATER_FLOWING)
    if not w.any():
        return False
    return bool(w[0].any() or w[-1].any() or w[:, 0].any() or w[:, -1].any()
                or w[:, :, 0].any() or w[:, :, -1].any())


class JavaRandom:
    """java.util.Random"""

    __slots__ = ("seed",)

    def __init__(self, seed: int = 0):
        self.set_seed(seed)

    def set_seed(self, seed: int):
        self.seed = (seed ^ 0x5DEECE66D) & MASK48

    def next(self, bits: int) -> int:
        self.seed = (self.seed * 0x5DEECE66D + 0xB) & MASK48
        r = self.seed >> (48 - bits)
        if bits == 32 and r >> 31:
            r -= 1 << 32
        return r

    def next_int(self, n: int) -> int:
        if n <= 0:
            raise ValueError("n must be positive")
        while True:                                    # next(31), inlined: the generators' hottest call
            self.seed = s = (self.seed * 0x5DEECE66D + 0xB) & MASK48
            bits = s >> 17
            if n & -n == n:
                return (n * bits) >> 31
            val = bits % n
            if bits - val + (n - 1) < 2147483648:
                return val

    def next_long(self) -> int:
        return _s64((self.next(32) << 32) + self.next(32))

    def next_double(self) -> float:
        return ((self.next(26) << 27) + self.next(27)) * (1.0 / (1 << 53))

    def next_float(self) -> np.float32:
        self.seed = s = (self.seed * 0x5DEECE66D + 0xB) & MASK48
        return np.float32((s >> 24) / 16777216.0)


# ------------------------------------------------------------------ Perlin noise (NoiseGeneratorPerlin)


def _floor_int(a: np.ndarray) -> np.ndarray:
    """Java: int i = (int) d; if (d < i) i--;"""
    t = np.trunc(a)
    t = np.clip(t, -2147483648.0, 2147483647.0)
    i = t.astype(np.int64)
    return np.where(a < t, i - 1, i)


def _fade(t):
    return t * t * t * (t * (t * 6.0 - 15.0) + 10.0)


def _lerp(t, a, b):
    return a + t * (b - a)


def _grad3(h, x, y, z):
    h = h & 15
    u = np.where(h < 8, x, y)
    v = np.where(h < 4, y, np.where((h == 12) | (h == 14), x, z))
    return np.where(h & 1, -u, u) + np.where(h & 2, -v, v)


def _grad2(h, x, z):
    h = h & 15
    u = (1 - ((h & 8) >> 3)) * x
    v = np.where(h < 4, 0.0, np.where((h == 12) | (h == 14), x, z))
    return np.where(h & 1, -u, u) + np.where(h & 2, -v, v)


class Perlin:
    def __init__(self, rnd: JavaRandom):
        self.xo = rnd.next_double() * 256.0
        self.yo = rnd.next_double() * 256.0
        self.zo = rnd.next_double() * 256.0
        p = list(range(256))
        for j in range(256):
            k = rnd.next_int(256 - j) + j
            p[j], p[k] = p[k], p[j]
        self.p = np.array(p + p, np.int64)

    def add(self, out: np.ndarray, x: float, y: float, z: float, nx: int, ny: int, nz: int,
            sx: float, sy: float, sz: float, amp: float):
        """out has shape (nx, nz, ny) (or (nx, nz) when ny == 1)."""
        p = self.p
        X = (x + np.arange(nx, dtype=np.float64)) * sx + self.xo
        Z = (z + np.arange(nz, dtype=np.float64)) * sz + self.zo
        xi = _floor_int(X)
        zi = _floor_int(Z)
        xf = X - xi
        zf = Z - zi
        xa = xi & 255
        za = zi & 255
        u = _fade(xf)[:, None]
        w = _fade(zf)[None, :]
        inv = 1.0 / amp
        if ny == 1:
            xf2 = xf[:, None]
            zf2 = zf[None, :]
            a = p[xa][:, None]           # permutations[k4] + 0
            j1 = p[a] + za[None, :]
            k1 = p[xa + 1][:, None]
            l1 = p[k1] + za[None, :]
            d9 = _lerp(u, _grad2(p[j1], xf2, zf2), _grad3(p[l1], xf2 - 1.0, 0.0, zf2))
            d11 = _lerp(u, _grad3(p[j1 + 1], xf2, 0.0, zf2 - 1.0), _grad3(p[l1 + 1], xf2 - 1.0, 0.0, zf2 - 1.0))
            out += _lerp(w, d9, d11) * inv
            return
        Y = (y + np.arange(ny, dtype=np.float64)) * sy + self.yo
        yi = _floor_int(Y)
        yf = Y - yi
        ya = yi & 255
        # Beta quirk: the corner gradients are computed at the first y of each noise cell and reused
        # (with that first y) for the following points of the same cell; only the fade uses each y.
        first = np.zeros(ny, np.int64)
        for j in range(1, ny):
            first[j] = first[j - 1] if ya[j] == ya[j - 1] else j
        v = _fade(yf)[None, None, :]
        u = u[:, :, None]
        w = w[:, :, None]
        X3 = xf[:, None, None]
        Y3 = yf[first][None, None, :]
        Z3 = zf[None, :, None]
        A = p[xa][:, None, None] + ya[None, None, :]       # k2
        AA = p[A] + za[None, :, None]                       # l7
        AB = p[A + 1] + za[None, :, None]                   # i8
        B = p[xa + 1][:, None, None] + ya[None, None, :]    # j8
        BA = p[B] + za[None, :, None]                       # k8
        BB = p[B + 1] + za[None, :, None]                   # l8
        d13 = _lerp(u, _grad3(p[AA], X3, Y3, Z3), _grad3(p[BA], X3 - 1.0, Y3, Z3))
        d15 = _lerp(u, _grad3(p[AB], X3, Y3 - 1.0, Z3), _grad3(p[BB], X3 - 1.0, Y3 - 1.0, Z3))
        d16 = _lerp(u, _grad3(p[AA + 1], X3, Y3, Z3 - 1.0), _grad3(p[BA + 1], X3 - 1.0, Y3, Z3 - 1.0))
        d18 = _lerp(u, _grad3(p[AB + 1], X3, Y3 - 1.0, Z3 - 1.0), _grad3(p[BB + 1], X3 - 1.0, Y3 - 1.0, Z3 - 1.0))
        d28 = _lerp(v, d13, d15)
        d29 = _lerp(v, d16, d18)
        out += _lerp(w, d28, d29) * inv


class PerlinOctaves:
    def __init__(self, rnd: JavaRandom, n: int):
        self.octaves = [Perlin(rnd) for _ in range(n)]

    def noise(self, x: float, y: float, z: float, nx: int, ny: int, nz: int, sx: float, sy: float, sz: float) -> np.ndarray:
        out = np.zeros((nx, nz, ny) if ny != 1 else (nx, nz), np.float64)
        amp = 1.0
        for o in self.octaves:
            o.add(out, x, y, z, nx, ny, nz, sx * amp, sy * amp, sz * amp, amp)
            amp /= 2.0
        return out

    def noise2d(self, x: int, z: int, nx: int, nz: int, sx: float, sz: float) -> np.ndarray:
        return self.noise(float(x), 10.0, float(z), nx, 1, nz, sx, 1.0, sz)


# ------------------------------------------------------------------ simplex noise (NoiseGenerator2)

_F2 = 0.5 * (math.sqrt(3.0) - 1.0)
_G2 = (3.0 - math.sqrt(3.0)) / 6.0
_GRAD2 = np.array([[1, 1], [-1, 1], [1, -1], [-1, -1], [1, 0], [-1, 0], [1, 0], [-1, 0],
                   [0, 1], [0, -1], [0, 1], [0, -1]], np.float64)


def _wrap(d):
    t = np.trunc(d).astype(np.int64)
    return np.where(d > 0.0, t, t - 1)


class Simplex:
    def __init__(self, rnd: JavaRandom):
        self.xo = rnd.next_double() * 256.0
        self.yo = rnd.next_double() * 256.0
        self.zo = rnd.next_double() * 256.0
        p = list(range(256))
        for j in range(256):
            k = rnd.next_int(256 - j) + j
            p[j], p[k] = p[k], p[j]
        self.p = np.array(p + p, np.int64)

    def add(self, out, x: float, z: float, nx: int, nz: int, sx: float, sz: float, amp: float):
        p = self.p
        d5 = ((x + np.arange(nx, dtype=np.float64)) * sx + self.xo)[:, None]
        d6 = ((z + np.arange(nz, dtype=np.float64)) * sz + self.yo)[None, :]
        d5, d6 = np.broadcast_arrays(d5, d6)
        d10 = (d5 + d6) * _F2
        j1 = _wrap(d5 + d10)
        k1 = _wrap(d6 + d10)
        d11 = (j1 + k1).astype(np.float64) * _G2
        d12 = j1 - d11
        d13 = k1 - d11
        d14 = d5 - d12
        d15 = d6 - d13
        first = d14 > d15
        l1 = np.where(first, 1, 0)
        i2 = np.where(first, 0, 1)
        d16 = (d14 - l1) + _G2
        d17 = (d15 - i2) + _G2
        d18 = (d14 - 1.0) + 2.0 * _G2
        d19 = (d15 - 1.0) + 2.0 * _G2
        j2 = j1 & 255
        k2 = k1 & 255
        g0 = p[j2 + p[k2]] % 12
        g1 = p[j2 + l1 + p[k2 + i2]] % 12
        g2 = p[j2 + 1 + p[k2 + 1]] % 12

        def corner(g, a, b):
            t = 0.5 - a * a - b * b
            tt = t * t
            val = tt * tt * (_GRAD2[g, 0] * a + _GRAD2[g, 1] * b)
            return np.where(t < 0.0, 0.0, val)

        out += 70.0 * (corner(g0, d14, d15) + corner(g1, d16, d17) + corner(g2, d18, d19)) * amp


class SimplexOctaves:
    def __init__(self, rnd: JavaRandom, n: int):
        self.octaves = [Simplex(rnd) for _ in range(n)]

    def noise(self, x: float, z: float, nx: int, nz: int, sx: float, sz: float, freq_mul: float, amp_mul: float = 0.5):
        sx /= 1.5
        sz /= 1.5
        out = np.zeros((nx, nz), np.float64)
        d6 = 1.0
        d7 = 1.0
        for o in self.octaves:
            o.add(out, x, z, nx, nz, sx * d7, sz * d7, 0.55 / d6)
            d7 *= freq_mul
            d6 *= amp_mul
        return out


# ------------------------------------------------------------------ biomes (WorldChunkManager / MobSpawnerBase)

BIOMES = ["rainforest", "swampland", "seasonal_forest", "forest", "savanna", "shrubland", "taiga", "desert",
          "plains", "ice_desert", "tundra"]


def _biome(t: float, h: float) -> str:
    t = float(np.float32(t))
    h = float(np.float32(np.float32(h) * np.float32(t)))
    if t < float(np.float32(0.1)):
        return "tundra"
    if h < float(np.float32(0.2)):
        if t < 0.5:
            return "tundra"
        if t < float(np.float32(0.95)):
            return "savanna"
        return "desert"
    if h > 0.5 and t < float(np.float32(0.7)):
        return "swampland"
    if t < 0.5:
        return "taiga"
    if t < float(np.float32(0.97)):
        return "shrubland" if h < float(np.float32(0.35)) else "forest"
    if h < float(np.float32(0.45)):
        return "plains"
    if h < float(np.float32(0.9)):
        return "seasonal_forest"
    return "rainforest"


_LOOKUP = [_biome(np.float32(i) / np.float32(63.0), np.float32(j) / np.float32(63.0))
           for j in range(64) for i in range(64)]  # index i + j * 64


class BiomeSource:
    def __init__(self, seed: int):
        self.temp = SimplexOctaves(JavaRandom(_s64(seed * 9871)), 4)
        self.hum = SimplexOctaves(JavaRandom(_s64(seed * 39811)), 4)
        self.var = SimplexOctaves(JavaRandom(_s64(seed * 543321)), 2)

    def generate(self, x: int, z: int, nx: int = 16, nz: int = 16):
        """temperature, humidity (nx, nz) and biome names, as loadBlockGeneratorData."""
        t = self.temp.noise(x, z, nx, nz, 0.02500000037252903, 0.02500000037252903, 0.25)
        h = self.hum.noise(x, z, nx, nz, 0.05000000074505806, 0.05000000074505806, 0.3333333333333333)
        v = self.var.noise(x, z, nx, nz, 0.25, 0.25, 0.5882352941176471)
        d = v * 1.1 + 0.5
        d3 = (t * 0.15 + 0.7) * 0.99 + d * 0.01
        d4 = (h * 0.15 + 0.5) * 0.998 + d * 0.002
        d3 = 1.0 - (1.0 - d3) * (1.0 - d3)
        d3 = np.clip(d3, 0.0, 1.0)
        d4 = np.clip(d4, 0.0, 1.0)
        bi = (d3 * 63.0).astype(np.int64) + (d4 * 63.0).astype(np.int64) * 64
        names = np.array(_LOOKUP, dtype=object)[bi]
        return d3, d4, names


# ------------------------------------------------------------------ MathHelper (float tables)

_SIN = np.array([np.float32(math.sin(i * math.pi * 2.0 / 65536.0)) for i in range(65536)], np.float32)
_F = np.float32
_K_SIN = _F(10430.38)


def _sin(f) -> np.float32:
    return _SIN[int(_F(f) * _K_SIN) & 0xFFFF]


def _cos(f) -> np.float32:
    return _SIN[int(_F(_F(f) * _K_SIN) + _F(16384.0)) & 0xFFFF]


def _floor_d(d: float) -> int:
    i = int(d)
    return i - 1 if d < i else i


# ------------------------------------------------------------------ the chunk generator (ChunkProviderGenerate)


class BetaGenerator:
    def __init__(self, seed: int):
        self.seed = _s64(seed)
        r = JavaRandom(self.seed)
        self.min_limit = PerlinOctaves(r, 16)
        self.max_limit = PerlinOctaves(r, 16)
        self.main = PerlinOctaves(r, 8)
        self.sand_gravel = PerlinOctaves(r, 4)
        self.stone_depth = PerlinOctaves(r, 4)
        self.scale = PerlinOctaves(r, 10)
        self.depth = PerlinOctaves(r, 16)
        self.biomes = BiomeSource(self.seed)
        self._cave_cache: Dict[Tuple[int, int], list] = {}

    # ---------------------------------------------------------- density field
    def _density(self, x: int, z: int, temp: np.ndarray, hum: np.ndarray) -> np.ndarray:
        nx, ny, nz = 5, 17, 5
        d = 684.412
        scale = self.scale.noise2d(x, z, nx, nz, 1.121, 1.121)
        depth = self.depth.noise2d(x, z, nx, nz, 200.0, 200.0)
        main = self.main.noise(x, 0, z, nx, ny, nz, d / 80.0, d / 160.0, d / 80.0)
        lo = self.min_limit.noise(x, 0, z, nx, ny, nz, d, d, d)
        hi = self.max_limit.noise(x, 0, z, nx, ny, nz, d, d, d)
        out = np.empty((nx, nz, ny), np.float64)
        step = 16 // nx
        for a in range(nx):
            k2 = a * step + step // 2
            for b in range(nz):
                i3 = b * step + step // 2
                d2 = temp[k2, i3]
                d3 = hum[k2, i3] * d2
                d4 = 1.0 - d3
                d4 *= d4
                d4 *= d4
                d4 = 1.0 - d4
                d5 = (scale[a, b] + 256.0) / 512.0
                d5 *= d4
                if d5 > 1.0:
                    d5 = 1.0
                d6 = depth[a, b] / 8000.0
                if d6 < 0.0:
                    d6 = -d6 * 0.3
                d6 = d6 * 3.0 - 2.0
                if d6 < 0.0:
                    d6 /= 2.0
                    if d6 < -1.0:
                        d6 = -1.0
                    d6 /= 1.4
                    d6 /= 2.0
                    d5 = 0.0
                else:
                    if d6 > 1.0:
                        d6 = 1.0
                    d6 /= 8.0
                if d5 < 0.0:
                    d5 = 0.0
                d5 += 0.5
                d6 = (d6 * ny) / 16.0
                d7 = ny / 2.0 + d6 * 4.0
                for c in range(ny):
                    d9 = ((c - d7) * 12.0) / d5
                    if d9 < 0.0:
                        d9 *= 4.0
                    d10 = lo[a, b, c] / 512.0
                    d11 = hi[a, b, c] / 512.0
                    d12 = (main[a, b, c] / 10.0 + 1.0) / 2.0
                    if d12 < 0.0:
                        d8 = d10
                    elif d12 > 1.0:
                        d8 = d11
                    else:
                        d8 = d10 + (d11 - d10) * d12
                    d8 -= d9
                    if c > ny - 4:
                        d13 = float(_F(c - (ny - 4)) / _F(3.0))
                        d8 = d8 * (1.0 - d13) + -10.0 * d13
                    out[a, b, c] = d8
        return out

    def _terrain(self, cx: int, cz: int, blocks: np.ndarray, temp: np.ndarray):
        q = self._density(cx * 4, cz * 4, *self._th)
        for i1 in range(4):
            for j1 in range(4):
                for k1 in range(16):
                    d1 = q[i1, j1, k1]
                    d2 = q[i1, j1 + 1, k1]
                    d3 = q[i1 + 1, j1, k1]
                    d4 = q[i1 + 1, j1 + 1, k1]
                    d5 = (q[i1, j1, k1 + 1] - d1) * 0.125
                    d6 = (q[i1, j1 + 1, k1 + 1] - d2) * 0.125
                    d7 = (q[i1 + 1, j1, k1 + 1] - d3) * 0.125
                    d8 = (q[i1 + 1, j1 + 1, k1 + 1] - d4) * 0.125
                    for l1 in range(8):
                        d10 = d1
                        d11 = d2
                        d12 = (d3 - d1) * 0.25
                        d13 = (d4 - d2) * 0.25
                        y = k1 * 8 + l1
                        for i2 in range(4):
                            x = i2 + i1 * 4
                            d15 = d10
                            d16 = (d11 - d10) * 0.25
                            for k2 in range(4):
                                z = j1 * 4 + k2
                                b = 0
                                if y < SEA_LEVEL:
                                    b = ICE if (temp[x, z] < 0.5 and y >= SEA_LEVEL - 1) else WATER
                                if d15 > 0.0:
                                    b = STONE
                                blocks[x, z, y] = b
                                d15 += d16
                            d10 += d12
                            d11 += d13
                        d1 += d5
                        d2 += d6
                        d3 += d7
                        d4 += d8

    def _surface(self, cx: int, cz: int, blocks: np.ndarray, biomes, rnd: JavaRandom):
        d = 0.03125
        sand = self.sand_gravel.noise(cx * 16, cz * 16, 0.0, 16, 16, 1, d, d, 1.0)[:, 0, :]  # (x, "y"=z)
        gravel = self.sand_gravel.noise(cx * 16, 109.0134, cz * 16, 16, 1, 16, d, 1.0, d)
        stone = self.stone_depth.noise(cx * 16, cz * 16, 0.0, 16, 16, 1, d * 2.0, d * 2.0, d * 2.0)[:, 0, :]
        M, A = 0x5DEECE66D, 0xB
        seed = rnd.seed
        sand_l = sand.tolist()
        gravel_l = gravel.tolist()
        stone_l = stone.tolist()
        for k in range(16):          # z
            for l in range(16):      # x
                desert = biomes[l, k] == "desert"
                # three nextDouble(), inlined java.util.Random
                dbl = []
                for _ in range(3):
                    seed = (seed * M + A) & MASK48
                    hi = seed >> 22
                    seed = (seed * M + A) & MASK48
                    dbl.append(((hi << 27) + (seed >> 21)) * (1.0 / (1 << 53)))
                flag = sand_l[l][k] + dbl[0] * 0.2 > 0.0
                flag1 = gravel_l[l][k] + dbl[1] * 0.2 > 3.0
                i1 = int(stone_l[l][k] / 3.0 + 3.0 + dbl[2] * 0.25)
                j1 = -1
                top = SAND if desert else GRASS
                filler = SAND if desert else DIRT
                col = blocks[l, k].tolist()
                for y in range(127, -1, -1):
                    while True:  # nextInt(5)
                        seed = (seed * M + A) & MASK48
                        bits = seed >> 17
                        val = bits % 5
                        if bits - val + 4 < 2147483648:
                            break
                    if y <= val:
                        col[y] = BEDROCK
                        continue
                    b = col[y]
                    if b == 0:
                        j1 = -1
                        continue
                    if b != STONE:
                        continue
                    if j1 == -1:
                        if i1 <= 0:
                            top = 0
                            filler = STONE
                        elif SEA_LEVEL - 4 <= y <= SEA_LEVEL + 1:
                            top = SAND if desert else GRASS
                            filler = SAND if desert else DIRT
                            if flag1:
                                top = 0
                                filler = GRAVEL
                            if flag:
                                top = SAND
                                filler = SAND
                        if y < SEA_LEVEL and top == 0:
                            top = WATER
                        j1 = i1
                        col[y] = top if y >= SEA_LEVEL - 1 else filler
                        continue
                    if j1 <= 0:
                        continue
                    j1 -= 1
                    col[y] = filler
                    if j1 == 0 and filler == SAND:
                        seed = (seed * M + A) & MASK48  # nextInt(4): power of two
                        j1 = (4 * (seed >> 17)) >> 31
                        filler = SANDSTONE
                blocks[l, k] = col
        rnd.seed = seed

    # ---------------------------------------------------------- caves (MapGenCaves)
    def _caves(self, cx: int, cz: int, blocks: np.ndarray):
        rnd = JavaRandom(self.seed)
        l = (_jdiv(rnd.next_long(), 2)) * 2 + 1
        l1 = (_jdiv(rnd.next_long(), 2)) * 2 + 1
        for i1 in range(cx - 8, cx + 9):
            for j1 in range(cz - 8, cz + 9):
                rnd.set_seed(_s64(i1 * l + j1 * l1) ^ self.seed)
                self._cave_source(rnd, i1, j1, cx, cz, blocks)

    def _cave_source(self, rnd: JavaRandom, i: int, j: int, cx: int, cz: int, blocks):
        n = rnd.next_int(rnd.next_int(rnd.next_int(40) + 1) + 1)
        if rnd.next_int(15) != 0:
            n = 0
        for _ in range(n):
            d = float(i * 16 + rnd.next_int(16))
            d1 = float(rnd.next_int(rnd.next_int(120) + 8))
            d2 = float(j * 16 + rnd.next_int(16))
            k1 = 1
            if rnd.next_int(4) == 0:
                self._tunnel(rnd, cx, cz, blocks, d, d1, d2, _F(_F(1.0) + rnd.next_float() * _F(6.0)),
                             _F(0.0), _F(0.0), -1, -1, 0.5)
                k1 += rnd.next_int(4)
            for _ in range(k1):
                f = _F(_F(rnd.next_float() * _F(3.141593)) * _F(2.0))
                f1 = _F(_F(_F(rnd.next_float() - _F(0.5)) * _F(2.0)) / _F(8.0))
                f2 = _F(_F(rnd.next_float() * _F(2.0)) + rnd.next_float())
                self._tunnel(rnd, cx, cz, blocks, d, d1, d2, f2, f, f1, 0, 0, 1.0)

    def _tunnel(self, rnd: JavaRandom, i: int, j: int, blocks, d: float, d1: float, d2: float,
                f, f1, f2, k: int, l: int, d3: float):
        d4 = float(i * 16 + 8)
        d5 = float(j * 16 + 8)
        f3 = _F(0.0)
        f4 = _F(0.0)
        random = JavaRandom(rnd.next_long())
        if l <= 0:
            i1 = 8 * 16 - 16
            l = i1 - random.next_int(i1 // 4)
        room = False
        if k == -1:
            k = l // 2
            room = True
        j1 = random.next_int(l // 2) + l // 4
        steep = random.next_int(6) == 0
        while k < l:
            d6 = 1.5 + float(_F(_F(_sin(_F(_F(k) * _F(3.141593)) / _F(l))) * f) * _F(1.0))
            d7 = d6 * d3
            f5 = _cos(f2)
            f6 = _sin(f2)
            d += float(_F(_cos(f1) * f5))
            d1 += float(f6)
            d2 += float(_F(_sin(f1) * f5))
            f2 = _F(f2 * (_F(0.92) if steep else _F(0.7)))
            f2 = _F(f2 + _F(f4 * _F(0.1)))
            f1 = _F(f1 + _F(f3 * _F(0.1)))
            f4 = _F(f4 * _F(0.9))
            f3 = _F(f3 * _F(0.75))
            a = random.next_float()
            b = random.next_float()
            c = random.next_float()
            f4 = _F(f4 + _F(_F(_F(a - b) * c) * _F(2.0)))
            a = random.next_float()
            b = random.next_float()
            c = random.next_float()
            f3 = _F(f3 + _F(_F(_F(a - b) * c) * _F(4.0)))
            if not room and k == j1 and f > _F(1.0):
                w1 = _F(_F(random.next_float() * _F(0.5)) + _F(0.5))
                self._tunnel(rnd, i, j, blocks, d, d1, d2, w1, _F(f1 - _F(1.570796)), _F(f2 / _F(3.0)), k, l, 1.0)
                w2 = _F(_F(random.next_float() * _F(0.5)) + _F(0.5))
                self._tunnel(rnd, i, j, blocks, d, d1, d2, w2, _F(f1 + _F(1.570796)), _F(f2 / _F(3.0)), k, l, 1.0)
                return
            if not room and random.next_int(4) == 0:
                k += 1
                continue
            d8 = d - d4
            d9 = d2 - d5
            d10 = float(l - k)
            d11 = float(_F(_F(f + _F(2.0)) + _F(16.0)))
            if (d8 * d8 + d9 * d9) - d10 * d10 > d11 * d11:
                return
            if d < d4 - 16.0 - d6 * 2.0 or d2 < d5 - 16.0 - d6 * 2.0 or d > d4 + 16.0 + d6 * 2.0 or d2 > d5 + 16.0 + d6 * 2.0:
                k += 1
                continue
            x0 = _floor_d(d - d6) - i * 16 - 1
            x1 = (_floor_d(d + d6) - i * 16) + 1
            y0 = _floor_d(d1 - d7) - 1
            y1 = _floor_d(d1 + d7) + 1
            z0 = _floor_d(d2 - d6) - j * 16 - 1
            z1 = (_floor_d(d2 + d6) - j * 16) + 1
            x0 = max(x0, 0)
            x1 = min(x1, 16)
            y0 = max(y0, 1)
            y1 = min(y1, 120)
            z0 = max(z0, 0)
            z1 = min(z1, 16)
            if water_in_box(blocks, x0, x1, y0, y1, z0, z1):
                k += 1
                continue
            for xx in range(x0, x1):
                d12 = ((xx + i * 16) + 0.5 - d) / d6
                for zz in range(z0, z1):
                    d13 = ((zz + j * 16) + 0.5 - d2) / d6
                    if d12 * d12 + d13 * d13 >= 1.0:
                        continue
                    col = blocks[xx, zz]
                    grass = False
                    yw = y1               # the block written is one above the one tested (as in the game)
                    yt = y1 - 1
                    while yt >= y0:
                        d14 = (yt + 0.5 - d1) / d7
                        if d14 > -0.7 and d12 * d12 + d14 * d14 + d13 * d13 < 1.0:
                            b = col[yw]
                            if b == GRASS:
                                grass = True
                            if b == STONE or b == DIRT or b == GRASS:
                                if yt < 10:
                                    col[yw] = LAVA_FLOWING
                                else:
                                    col[yw] = 0
                                    if grass and col[yw - 1] == DIRT:
                                        col[yw - 1] = GRASS
                        yw -= 1
                        yt -= 1
            if room:
                break
            k += 1

    # ---------------------------------------------------------- public
    def chunk(self, cx: int, cz: int, lift=None) -> Tuple[np.ndarray, np.ndarray]:
        """Blocks (x, z, y) uint8 of a freshly generated, unpopulated chunk, and the biome names (x, z).
        ``lift`` [x, z]: blocks (fractions too) to move the terrain up (down if negative), see lift.py."""
        seed = _s64(cx * 0x4F9939F508 + cz * 0x1EF1565BD5)
        temp, hum, names = self.biomes.generate(cx * 16, cz * 16)
        self._th = (temp, hum)
        blocks = np.zeros((16, 16, 128), np.uint8)
        self._terrain(cx, cz, blocks, temp)
        self._surface(cx, cz, blocks, names, JavaRandom(seed))
        lifted = lift is not None and bool(np.any(lift))
        before = blocks.copy() if lifted else None
        self._caves(cx, cz, blocks)
        if not lifted:
            return blocks, names
        from .lift import density_field, lifted_rock, move_caves

        q = self._density(cx * 4, cz * 4, *self._th)
        moved = lifted_rock(density_field(q), lift, SEA_LEVEL - 1, ice=np.asarray(temp) < 0.5)
        self._surface(cx, cz, moved, names, JavaRandom(seed))
        move_caves(moved, before, blocks, lift)
        keep = np.asarray(lift) == 0                        # the game's own columns, exactly
        moved[keep] = blocks[keep]
        return moved, names
