"""Terrain generator of Minecraft Beta 1.8 - 1.6.4 (ChunkProviderGenerate), for the ring of terrain
WorldBridge writes around a converted world (see ring.py).

Same noises as Beta 1.7.3 (betagen) with the Beta 1.8 changes: the height comes from the biomes
(5x5 biome samples weighted by distance, each with its min / max height), the surface from the
biome's top / filler blocks, sea level 63 (water up to y 62).  Biomes: genlayers.

Validated on chunks generated by the games themselves (seed -3878429724685138167, code read from the
1.0 and 1.1 jars): biomes identical to cubiomes; surface at the same height in 99.0 % of the columns
on 1,023 chunks of 1.0 (924 identical chunks) and 99.5 % on 1,442 chunks of 1.1 (1,366); air, water
and rock identical in 99.8 % of the blocks. The rest is the game's decoration (mineshafts, dungeons,
lakes, villages, sand around water).
Caves and ravines: carvers.py (MapGenCaves / MapGenRavine of 1.0 / 1.1).

1.2 - 1.6 (code read from the 1.2.5 and 1.6.4 jars): the same terrain, caves and ravines; only the
biomes change (the jungle, taiga in the cold lands from 1.3, "Large Biomes" from 1.3, taller hills
from 1.3; 1.3.2 - 1.6.4 have the same terrain, caves and biome table).  On the 1,322 chunks of a 1.6.4 world (same seed): biomes identical, air / water / rock
identical in 98.97 % of the blocks, the ground at the same height in 97.9 % of the columns.
"""

from __future__ import annotations

from typing import Tuple

import numpy as np

from .betagen import (BEDROCK, DIRT, GRASS, ICE, SAND, SANDSTONE, STONE, WATER, JavaRandom, PerlinOctaves, _s64)
from .genlayers import Stack
from .carvers import chunk_top_of as _chunk_top_of
from .lift import density_field, lifted_rock, move_caves

_F = np.float32
SEA_LEVEL = 63          # water up to y 62
MYCELIUM = 110

# biome id -> (min height, max height, temperature), as in BiomeGenBase of each version
_HEIGHTS_10 = {0: (-1.0, 0.4, 0.5), 1: (0.1, 0.3, 0.8), 2: (0.1, 0.2, 2.0), 3: (0.2, 1.8, 0.2), 4: (0.1, 0.3, 0.7),
               5: (0.1, 0.4, 0.3), 6: (-0.2, 0.1, 0.8), 7: (-0.5, 0.0, 0.5), 10: (-1.0, 0.5, 0.0),
               11: (-0.5, 0.0, 0.0), 12: (0.1, 0.3, 0.0), 13: (0.2, 1.8, 0.0), 14: (0.2, 1.0, 0.9),
               15: (-1.0, 0.1, 0.9)}
_TOPS = {2: (SAND, SAND), 14: (MYCELIUM, DIRT), 15: (MYCELIUM, DIRT), 16: (SAND, SAND), 17: (SAND, SAND)}
VERSIONS = ("b1.8", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6")


def _heights(version: str):
    """BiomeGenBase of each version (read from the b1.8.1, 1.0, 1.1, 1.2.5, 1.3.2, 1.4.7, 1.5.2 and 1.6.4 code)."""
    t = dict(_HEIGHTS_10)
    if version == "b1.8":
        t[0] = (-1.0, 0.5, 0.5)                         # Beta 1.8.1: rougher ocean floor (0.4 from 1.0)
    if version != "b1.8" and version != "1.0":
        # lower mountains, colder taiga, and the biomes added by 1.1 (beach, hills, mountain edge)
        t.update({3: (0.2, 1.3, 0.2), 5: (0.1, 0.4, 0.05), 13: (0.2, 1.2, 0.0),
                  16: (0.0, 0.1, 0.8), 17: (0.2, 0.7, 2.0), 18: (0.2, 0.6, 0.7), 19: (0.2, 0.7, 0.05),
                  20: (0.2, 0.8, 0.2)})
    if version in ("1.2", "1.3", "1.4", "1.5", "1.6"):
        # the jungle; its hills have min > max (as in the game: tall, rugged hills)
        t.update({21: (0.2, 0.4, 1.2), 22: (1.8, 0.2, 1.2)})
    if version in _TALLER_HILLS:
        # taller mountains and hills (1.3: the same table up to 1.6.4)
        t.update({3: (0.3, 1.5, 0.2), 13: (0.3, 1.3, 0.0), 17: (0.3, 0.8, 2.0), 18: (0.3, 0.7, 0.7),
                  19: (0.3, 0.8, 0.05), 22: (1.8, 0.5, 1.2)})
    return t


_TALLER_HILLS = ("1.3", "1.4", "1.5", "1.6")


class ReleaseGenerator:
    def __init__(self, seed: int, version: str = "1.0", caves: bool = True, large_biomes: bool = False):
        from .carvers import ReleaseCarvers

        self.seed = _s64(seed)
        self.caves = caves
        self.carvers = ReleaseCarvers(self.seed)
        self.version = version
        self.table = _heights(version)
        self.stack = Stack(version, self.seed, large_biomes)
        r = JavaRandom(self.seed)
        self.n1 = PerlinOctaves(r, 16)
        self.n2 = PerlinOctaves(r, 16)
        self.n3 = PerlinOctaves(r, 8)
        self.n4 = PerlinOctaves(r, 4)
        self.n5 = PerlinOctaves(r, 10)
        self.n6 = PerlinOctaves(r, 16)
        pf = np.zeros(25, np.float32)
        for i in range(-2, 3):
            for j in range(-2, 3):
                pf[i + 2 + (j + 2) * 5] = _F(10.0) / np.sqrt(_F(i * i + j * j) + _F(0.2), dtype=np.float32)
        self.pf = pf

    # ---------------------------------------------------------- density field
    def _density(self, cx: int, cz: int, b4: np.ndarray) -> np.ndarray:
        x, z = cx * 4, cz * 4
        nx, ny, nz = 5, 17, 5
        d = 684.412
        n6 = self.n6.noise2d(x, z, nx, nz, 200.0, 200.0)
        n3 = self.n3.noise(x, 0, z, nx, ny, nz, d / 80.0, d / 160.0, d / 80.0)
        n1 = self.n1.noise(x, 0, z, nx, ny, nz, d, d, d)
        n2 = self.n2.noise(x, 0, z, nx, ny, nz, d, d, d)
        out = np.empty((nx, nz, ny))
        tab = self.table
        for k in range(nx):
            for l in range(nz):
                f = f1 = f2 = _F(0)
                cmin = _F(tab[b4[l + 2, k + 2]][0])
                for i1 in range(-2, 3):
                    for j1 in range(-2, 3):
                        lo, hi = tab[b4[l + j1 + 2, k + i1 + 2]][:2]
                        bmin, bmax = _F(lo), _F(hi)
                        f3 = _F(self.pf[i1 + 2 + (j1 + 2) * 5] / _F(bmin + _F(2.0)))
                        if bmin > cmin:
                            f3 = _F(f3 / _F(2.0))
                        f = _F(f + _F(bmax * f3))
                        f1 = _F(f1 + _F(bmin * f3))
                        f2 = _F(f2 + f3)
                f = _F(f / f2)
                f1 = _F(f1 / f2)
                f = _F(_F(f * _F(0.9)) + _F(0.1))
                f1 = _F(_F(_F(f1 * _F(4.0)) - _F(1.0)) / _F(8.0))
                d2 = n6[k, l] / 8000.0
                if d2 < 0.0:
                    d2 = -d2 * 0.3
                d2 = d2 * 3.0 - 2.0
                if d2 < 0.0:
                    d2 /= 2.0
                    if d2 < -1.0:
                        d2 = -1.0
                    d2 /= 1.4
                    d2 /= 2.0
                else:
                    if d2 > 1.0:
                        d2 = 1.0
                    d2 /= 8.0
                for k1 in range(ny):
                    d3 = float(f1) + d2 * 0.2
                    d3 = d3 * ny / 16.0
                    d5 = ny / 2.0 + d3 * 4.0
                    d7 = (k1 - d5) * 12.0 * 128.0 / 128.0 / float(f)
                    if d7 < 0.0:
                        d7 *= 4.0
                    d8 = n1[k, l, k1] / 512.0
                    d9 = n2[k, l, k1] / 512.0
                    d10 = (n3[k, l, k1] / 10.0 + 1.0) / 2.0
                    d6 = d8 if d10 < 0.0 else d9 if d10 > 1.0 else d8 + (d9 - d8) * d10
                    d6 -= d7
                    if k1 > ny - 4:
                        d11 = float(_F(k1 - (ny - 4)) / _F(3.0))
                        d6 = d6 * (1.0 - d11) + -10.0 * d11
                    out[k, l, k1] = d6
        return out

    @staticmethod
    def _terrain(q: np.ndarray, blocks: np.ndarray) -> None:
        for i1 in range(4):
            for j1 in range(4):
                for k1 in range(16):
                    d1, d2, d3, d4 = q[i1, j1, k1], q[i1, j1 + 1, k1], q[i1 + 1, j1, k1], q[i1 + 1, j1 + 1, k1]
                    d5 = (q[i1, j1, k1 + 1] - d1) * 0.125
                    d6 = (q[i1, j1 + 1, k1 + 1] - d2) * 0.125
                    d7 = (q[i1 + 1, j1, k1 + 1] - d3) * 0.125
                    d8 = (q[i1 + 1, j1 + 1, k1 + 1] - d4) * 0.125
                    for l1 in range(8):
                        d10, d11 = d1, d2
                        d12 = (d3 - d1) * 0.25
                        d13 = (d4 - d2) * 0.25
                        y = k1 * 8 + l1
                        for i2 in range(4):
                            x = i2 + i1 * 4
                            d16 = (d11 - d10) * 0.25
                            d15 = d10 - d16                 # as in the game: step back, then add before testing
                            for k2 in range(4):
                                d15 += d16
                                blocks[x, j1 * 4 + k2, y] = STONE if d15 > 0.0 else (WATER if y < SEA_LEVEL else 0)
                            d10 += d12
                            d11 += d13
                        d1 += d5
                        d2 += d6
                        d3 += d7
                        d4 += d8

    def _surface(self, cx: int, cz: int, blocks: np.ndarray, b1: np.ndarray, rnd: JavaRandom) -> None:
        d = 0.03125
        stone = self.n4.noise(cx * 16, cz * 16, 0.0, 16, 16, 1, d * 2.0, d * 2.0, d * 2.0)[:, 0, :].tolist()
        tab = self.table
        for k in range(16):          # z
            for l in range(16):      # x
                bid = int(b1[k, l])
                temp = tab.get(bid, (0, 0, 0.5))[2]
                btop, bfill = _TOPS.get(bid, (GRASS, DIRT))
                i1 = int(stone[l][k] / 3.0 + 3.0 + rnd.next_double() * 0.25)
                j1 = -1
                top, filler = btop, bfill
                col = blocks[l, k].tolist()
                seed = rnd.seed                              # rnd.next_int(5) of every block, inlined
                for y in range(len(col) - 1, -1, -1):
                    if y < 128:                              # (a lifted column may reach above 128)
                        seed = (seed * 0x5DEECE66D + 0xB) & 0xFFFFFFFFFFFF
                        bits = seed >> 17
                        val = bits % 5
                        if bits - val + 4 >= 2147483648:     # rejected draw: the loop goes on
                            rnd.seed = seed
                            val = rnd.next_int(5)
                            seed = rnd.seed
                        if y <= val:
                            col[y] = BEDROCK
                            continue
                    b = col[y]
                    if b == 0:
                        j1 = -1
                        continue
                    if b != STONE:
                        continue
                    if j1 == -1:
                        if i1 <= 0:
                            top, filler = 0, STONE
                        elif SEA_LEVEL - 4 <= y <= SEA_LEVEL + 1:
                            top, filler = btop, bfill
                        if y < SEA_LEVEL and top == 0:
                            top = ICE if temp < 0.15 else WATER
                        j1 = i1
                        col[y] = top if y >= SEA_LEVEL - 1 else filler
                        continue
                    if j1 > 0:
                        j1 -= 1
                        col[y] = filler
                        if j1 == 0 and filler == SAND:
                            rnd.seed = seed
                            j1 = rnd.next_int(4)
                            seed = rnd.seed
                            filler = SANDSTONE
                rnd.seed = seed
                blocks[l, k] = col

    # ---------------------------------------------------------- public
    def chunk(self, cx: int, cz: int, lift=None) -> Tuple[np.ndarray, np.ndarray]:
        """Blocks (x, z, y) uint8 of a freshly generated chunk and its biome ids (x, z).  ``lift``
        [x, z]: blocks (fractions too) to move the terrain up (down if negative), see lift.py."""
        seed = _s64(cx * 0x4F9939F508 + cz * 0x1EF1565BD5)
        b4 = self.stack.biomes4(cx * 4 - 2, cz * 4 - 2, 10, 10)
        b1 = self.stack.biomes(cx * 16, cz * 16, 16, 16)
        q = self._density(cx, cz, b4)
        blocks = np.zeros((16, 16, 128), np.uint8)
        self._terrain(q, blocks)
        self._surface(cx, cz, blocks, b1, JavaRandom(seed))
        lifted = lift is not None and bool(np.any(lift))
        before = blocks.copy() if lifted and self.caves else None
        if self.caves:
            self.carvers.carve(cx, cz, blocks, _chunk_top_of(b1, cx, cz, self._top_block, self._top_of))
        if not lifted:
            return blocks, b1.T.copy()
        # Anvil worlds (1.2+) are 256 blocks high: a column lifted above the generator's 128 keeps its top
        height = 256 if self.version not in ("b1.8", "1.0", "1.1") and float(np.max(lift)) > 0 else None
        moved = lifted_rock(density_field(q), lift, SEA_LEVEL - 1, height=height)
        self._surface(cx, cz, moved, b1, JavaRandom(seed))
        if before is not None:
            move_caves(moved, before, blocks, lift)
        keep = np.asarray(lift) == 0                        # the game's own columns, exactly
        moved[keep] = 0
        moved[keep, :blocks.shape[2]] = blocks[keep]
        return moved, b1.T.copy()

    def _top_of(self, x: int, z: int) -> int:
        return self._top_block(int(self.stack.biomes(x, z, 1, 1)[0, 0]))

    @staticmethod
    def _top_block(b: int) -> int:
        return _TOPS.get(b, (GRASS, DIRT))[0]
