"""Java 1.7 - 1.12: biome layers (up to 1.16), the terrain generator and the ring of Anvil targets."""
import numpy as np

from worldbridge.convert import TargetSpec, convert
from worldbridge.java.numeric import JavaNumericWorld, JavaNumericWriter, JavaWriteOptions
from worldbridge.model import Progress
from worldbridge.terrain.layers17 import Stack17
from worldbridge.terrain.modern import ModernGenerator

from .helpers import SyntheticWorld
from .layers17_snapshot import SNAP

SEED = -3878429724685138167


def test_biomes_identical_to_cubiomes():
    for version, seed, large, x, z, a4, a1 in SNAP:
        s = Stack17(version, seed, large)
        assert (s.biomes4(x // 4, z // 4, 16, 16) == np.array(a4)).all(), version
        if a1 is not None:
            assert (s.biomes(x, z, 24, 24) == np.array(a1)).all(), version


def test_terrain_and_caves_generated_by_minecraft_1_12_2():
    # chunk (19, 22) of seed -3878429724685138167 (extreme hills, stone beach, river) as generated by
    # Minecraft 1.12.2: air, water, rock and lava identical in every block, its caves included
    blocks, biomes, data = ModernGenerator(SEED, "1.12").chunk(19, 22)
    assert blocks.shape == (16, 16, 256) and set(np.unique(biomes)) == {0, 3, 7, 25}
    solid = np.isin(blocks, (1, 2, 3, 12, 13, 24))
    top = 255 - np.argmax(solid[:, :, ::-1], axis=2)
    assert top[:, 0].tolist() == [67, 65, 63, 61, 60, 59, 59, 58, 58, 58, 58, 58, 58, 58, 59, 60]
    assert top[0, :].tolist() == [67, 65, 63, 61, 59, 59, 59, 58, 58, 57, 57, 56, 56, 55, 54, 54]
    air = np.isin(blocks[:, :, 5:60], (0, 10, 11))
    assert int(air.sum()) == 1268
    for x, z, y in [(0, 0, 0), (6, 1, 29), (9, 1, 9), (11, 1, 34), (13, 2, 18), (14, 3, 10), (15, 2, 14), (15, 15, 20)]:
        assert air[x, z, y]


def test_1_8_settings_are_floats():
    assert ModernGenerator(SEED, "1.7").scales[2] == 684.412 / 80.0
    assert ModernGenerator(SEED, "1.8").scales[2] == float(np.float32(np.float32(684.412) / np.float32(80.0)))


def test_anvil_targets_1_7_to_1_12_get_a_ring(tmp_path):
    from worldbridge.terrain import policy, ring

    t = TargetSpec(family="java", java_mode="numeric", java_version_limit="1.12")
    assert policy.decide(t, True).kind == "ring"
    assert not ring.supported(t, "customized") and ring.supported(t, "amplified")
    src = SyntheticWorld(radius=1)
    src.info.level["RandomSeed"] = src.info.level["RandomSeed"].__class__(SEED)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    out = str(tmp_path / "a112")
    convert(hub, out, TargetSpec(family="java", java_mode="numeric", java_version_limit="1.12"))
    world = JavaNumericWorld(out)
    coords = set(world.chunk_coords(0))
    assert len(coords) > 4 + 40
    far = max(x for x, z in coords if z == 0)
    gen, bio, data = ModernGenerator(SEED, "1.12").chunk(far, 0)
    c = world.read_chunk(0, far, 0)
    assert not c.terrain_populated
    # the ring's outer edge is the game's own terrain, block data (podzol, red sand, clay colours) included
    assert (np.transpose(gen, (2, 1, 0))[:, :, 15] == np.asarray(c.blocks)[:, :, 15]).all()
    assert (np.transpose(data, (2, 1, 0))[:, :, 15] == np.asarray(c.data)[:, :, 15]).all()
    assert (np.asarray(c.biomes) == bio.T).all()
