"""Beta 1.8 - 1.1: biome layers and the terrain ring written around converted worlds."""
import numpy as np

from worldbridge.convert import TargetSpec, convert
from worldbridge.terrain.genlayers import Stack
from worldbridge.java.numeric import JavaNumericWorld, JavaNumericWriter, JavaWriteOptions
from worldbridge.terrain.releasegen import ReleaseGenerator
from worldbridge.model import Progress

from .genlayers_snapshot import SNAP
from .helpers import SyntheticWorld


def test_biomes_identical_to_cubiomes():
    for version, seed, x, z, a4, a1 in SNAP:
        s = Stack(version, seed)
        assert (s.biomes4(x // 4, z // 4, 12, 12) == np.array(a4)).all(), version
        assert (s.biomes(x, z, 24, 24) == np.array(a1)).all(), version


def test_terrain_generated_by_minecraft_1_0():
    # chunk (-20, 33) of seed -3878429724685138167 as generated by Minecraft 1.0 itself (surface
    # heights of its first row; validated on 1,023 game chunks)
    blocks, biomes = ReleaseGenerator(-3878429724685138167, "1.0").chunk(-20, 33)
    solid = np.isin(blocks, (1, 2, 3, 12, 13, 24))
    top = 127 - np.argmax(solid[:, :, ::-1], axis=2)
    assert top[:, 0].tolist() == REF_1_0_ROW
    assert blocks[:, :, 0].min() == 7                                         # bedrock floor


def test_1_1_targets_get_a_ring_without_raising_the_world(tmp_path):
    src = SyntheticWorld(radius=1)
    src.info.level["RandomSeed"] = src.info.level["RandomSeed"].__class__(12345)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    out = str(tmp_path / "r11")
    convert(hub, out, TargetSpec(family="java", java_mode="mcregion", java_version_limit="1.1"))
    world = JavaNumericWorld(out)
    coords = set(world.chunk_coords(0))
    assert coords >= {(x, z) for x in range(-4, 4) for z in range(-4, 4)}
    far = max(x for x, z in coords if z == 0)
    ring = world.read_chunk(0, far, 0)
    assert not ring.terrain_populated
    gen, _ = ReleaseGenerator(12345, "1.1").chunk(far, 0)
    assert (np.transpose(gen, (2, 1, 0))[:, :, 15] == np.asarray(ring.blocks[:128])[:, :, 15]).all()
    # no +1 shift: that is only for the Alpha / Beta sea
    before = np.asarray(src.read_chunk(0, 0, 0).blocks[:128])
    after = np.asarray(world.read_chunk(0, 0, 0).blocks[:128])
    assert (before[1:] == after[1:]).all()


REF_1_0_ROW = [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 59, 66, 73, 74, 75, 76]


def test_the_seed_of_1_16_and_newer_worlds_is_found():
    from worldbridge import nbt
    from worldbridge.convert import world_seed

    level = nbt.CompoundTag({"WorldGenSettings": nbt.CompoundTag({"seed": nbt.LongTag(-3878429724685138167)})})
    assert world_seed(level) == -3878429724685138167
    assert world_seed(nbt.CompoundTag({"RandomSeed": nbt.LongTag(5)})) == 5


def test_caves_and_ravines_as_generated_by_minecraft_1_0():
    # chunk (-5, 31) of seed -3878429724685138167, left undecorated by Minecraft 1.0: its cave air
    # below y 60 (3,329 blocks, a ravine through a cave) is identical to the game's, block by block
    blocks, _ = ReleaseGenerator(-3878429724685138167, "1.0").chunk(-5, 31)
    air = np.isin(blocks[:, :, 5:60], (0, 10))
    assert int(air.sum()) == 3329
    for x, z, y in [(0, 0, 24), (1, 7, 28), (2, 10, 12), (3, 11, 19), (4, 15, 11), (6, 3, 29), (7, 6, 17),
                    (8, 12, 15), (10, 4, 13), (11, 12, 12), (13, 3, 25), (14, 8, 4)]:
        assert air[x, z, y]


def test_1_1_biome_heights_differ_from_1_0():
    from worldbridge.terrain.releasegen import _heights

    assert _heights("1.0")[3][:2] == (0.2, 1.8) and _heights("1.1")[3][:2] == (0.2, 1.3)   # Extreme Hills
    assert _heights("1.1")[16][:2] == (0.0, 0.1)                                            # Beach


# ---------------------------------------------------------------- 1.2 - 1.6 (Anvil targets)

def test_biomes_of_1_2_to_1_6_identical_to_cubiomes():
    from .genlayers_snapshot import SNAP_16

    for version, seed, large, x, z, a4, a1 in SNAP_16:
        s = Stack(version, seed, large)
        assert (s.biomes4(x // 4, z // 4, 12, 12) == np.array(a4)).all(), version
        assert (s.biomes(x, z, 24, 24) == np.array(a1)).all(), version


def test_biome_heights_of_1_2_and_1_6():
    from worldbridge.terrain.releasegen import _heights

    assert _heights("1.2")[22][:2] == (1.8, 0.2) and _heights("1.6")[22][:2] == (1.8, 0.5)   # Jungle Hills
    assert _heights("1.2")[3][:2] == (0.2, 1.3) and _heights("1.6")[3][:2] == (0.3, 1.5)     # Extreme Hills
    assert _heights("1.3") == _heights("1.4") == _heights("1.5") == _heights("1.6")         # 1.3.2 - 1.6.4 jars


def _tall_world(level=150):
    class Tall(SyntheticWorld):
        def read_chunk(self, dim, cx, cz):
            c = super().read_chunk(dim, cx, cz)
            c.blocks[1:level] = 1
            c.blocks[level - 3:level] = 3
            c.blocks[level] = 2
            return c
    return Tall(radius=1)


def test_anvil_targets_1_2_to_1_6_get_a_ring_up_to_256(tmp_path):
    from worldbridge.terrain import policy

    t = TargetSpec(family="java", java_mode="numeric", java_version_limit="1.6")
    assert policy.decide(t, True).kind == "ring"
    src = _tall_world()
    src.info.level["RandomSeed"] = src.info.level["RandomSeed"].__class__(-3878429724685138167)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    out = str(tmp_path / "a16")
    convert(hub, out, TargetSpec(family="java", java_mode="numeric", java_version_limit="1.6"))
    world = JavaNumericWorld(out)
    coords = set(world.chunk_coords(0))
    assert len(coords) > 4 + 40
    # next to the converted mountain (ground at y 150) the ring rises above the generator's 128
    near = np.asarray(world.read_chunk(0, 1, 0).blocks)
    assert (near[140:, :, :2] != 0).any()
    # its outer edge is the game's own terrain
    far = max(x for x, z in coords if z == 0)
    gen, bio = ReleaseGenerator(-3878429724685138167, "1.6").chunk(far, 0)
    ring = world.read_chunk(0, far, 0)
    assert (np.transpose(gen, (2, 1, 0))[:, :, 15] == np.asarray(ring.blocks[:128])[:, :, 15]).all()
    assert (np.asarray(ring.biomes) == bio.T).all()


def test_terrain_and_caves_generated_by_minecraft_1_6_4():
    # chunk (0, 21) of seed -3878429724685138167, a jungle, as generated by Minecraft 1.6.4 (on the
    # 1,322 chunks of that world: biomes identical, air / water / rock identical in 98.97 % of the
    # blocks, the rest is the game's decoration: lakes, mineshafts, dungeons)
    blocks, biomes = ReleaseGenerator(-3878429724685138167, "1.6").chunk(0, 21)
    assert (biomes == 21).all()
    solid = np.isin(blocks, (1, 2, 3, 12, 13, 24))
    top = 127 - np.argmax(solid[:, :, ::-1], axis=2)
    # (the game's first row; at x 3 its decoration turned the top block into clay)
    assert top[:, 0].tolist() == [60, 60, 60, 60, 60, 60, 60, 61, 61, 61, 60, 60, 60, 60, 60, 60]
    air = np.isin(blocks[:, :, 5:50], (0, 10, 11))        # cave air and lava below y 50: block by block
    assert int(air.sum()) == 351
    for x, z, y in [(5, 0, 0), (3, 10, 4), (3, 9, 6), (4, 14, 7), (9, 12, 19), (2, 12, 20), (6, 10, 21), (12, 15, 22)]:
        assert air[x, z, y]
