"""Tables read from the game itself: the biomes of each version (Java 26.3's jar has 67) and the
map colours of every block (worldbridge/mapcolors.py, generated by tools/mapcolors.py)."""

from worldbridge import amulet_bridge as ab
from worldbridge import biomes
from worldbridge.mapcolors import MAP_COLORS, SEE_THROUGH
from worldbridge.mapview import block_color, is_air

# data/minecraft/worldgen/biome/*.json of the Java 26.3 client jar
JAVA_26_3 = {
    "badlands", "bamboo_jungle", "basalt_deltas", "beach", "birch_forest", "cherry_grove", "cold_ocean",
    "crimson_forest", "dappled_forest", "dark_forest", "deep_cold_ocean", "deep_dark", "deep_frozen_ocean",
    "deep_lukewarm_ocean", "deep_ocean", "desert", "dripstone_caves", "end_barrens", "end_highlands", "end_midlands",
    "eroded_badlands", "flower_forest", "forest", "frozen_ocean", "frozen_peaks", "frozen_river", "grove",
    "ice_spikes", "jagged_peaks", "jungle", "lukewarm_ocean", "lush_caves", "mangrove_swamp", "meadow",
    "mushroom_fields", "nether_wastes", "ocean", "old_growth_birch_forest", "old_growth_pine_taiga",
    "old_growth_spruce_taiga", "pale_garden", "plains", "river", "savanna", "savanna_plateau", "small_end_islands",
    "snowy_beach", "snowy_plains", "snowy_slopes", "snowy_taiga", "soul_sand_valley", "sparse_jungle", "stony_peaks",
    "stony_shore", "sulfur_caves", "sunflower_plains", "swamp", "taiga", "the_end", "the_void", "warm_ocean",
    "warped_forest", "windswept_forest", "windswept_gravelly_hills", "windswept_hills", "windswept_savanna",
    "wooded_badlands"}


def _names(family, version):
    return {biomes.modern_name(b) for b in biomes.available(family, version)}


def test_java_26_3_biomes_are_the_games():
    assert _names("java", (26, 3)) == JAVA_26_3
    assert "dappled_forest" not in _names("java", (26, 2)) and "sulfur_caves" in _names("java", (26, 2))


def test_bedrock_biomes_follow_bedrocks_own_versions():
    assert {"dappled_forest", "sulfur_caves"} <= _names("bedrock", (26, 50))
    assert "dappled_forest" not in _names("bedrock", (26, 20))       # 26.20 is not after Java's 26.3
    assert "pale_garden" not in _names("bedrock", (1, 21, 40)) and "pale_garden" in _names("bedrock", (1, 21, 50))


def test_new_biomes_translate_to_bedrock_ids():
    tm = ab.translation_manager()
    java = tm.get_version("java", ab.latest("java"))
    bedrock = tm.get_version("bedrock", (26, 50, 0))
    for bid, numeric in ((biomes.parse("dappled_forest"), 195), (biomes.parse("sulfur_caves"), 194)):
        universal = java.biome.to_universal("minecraft:" + biomes.modern_name(bid))
        assert bedrock.biome.pack(bedrock.biome.from_universal(universal)) == numeric


def test_map_colours_cover_every_java_block():
    names = set(ab.translation_manager().get_version("java", (26, 3, 0)).block.base_names("minecraft"))
    assert names <= set(MAP_COLORS) | SEE_THROUGH


def test_map_colours_are_the_games():
    assert block_color("minecraft:leaf_litter") == (102, 76, 51)                 # COLOR_BROWN
    assert block_color("minecraft:orange_poplar_leaves") == (216, 127, 51)       # the dappled forest
    assert block_color("minecraft:red_poplar_leaves") == (153, 51, 51)
    assert block_color("minecraft:yellow_poplar_leaves") == (229, 229, 51)
    assert block_color("minecraft:oak_leaves") == (0, 124, 0)                    # PLANT
    assert block_color("minecraft:lime_terracotta") == (103, 117, 53)
    assert block_color("minecraft:oxidized_cut_copper_stairs") == (22, 126, 134)
    assert block_color("minecraft:normal_stone_slab") == block_color("minecraft:stone")   # a Bedrock name
    assert is_air("minecraft:glass") and is_air("minecraft:torch") and not is_air("minecraft:water")
