"""Alpha 1.2 - Beta 1.7.3 terrain generator and the smooth border around converted worlds."""
import numpy as np

from worldbridge.convert import TargetSpec, convert
from worldbridge.terrain.betagen import BetaGenerator, JavaRandom
from worldbridge.java.numeric import JavaNumericWorld

from .helpers import SyntheticWorld


def test_java_random():
    assert JavaRandom(0).next(32) == -1155484576
    assert JavaRandom(0).next_double() == 0.730967787376657
    assert JavaRandom(0).next_long() == -4962768465676381896
    r = JavaRandom(42)
    assert [r.next_int(10) for _ in range(5)] == [0, 3, 8, 4, 0]


def test_heights_generated_by_the_game():
    # chunk (1, -4) of seed 4817984047639240568, as generated by Beta 1.7.3 itself: ground at y = 86
    # along its north-west corner (validated on 736 game chunks: 98.7 % of the columns identical, the
    # rest are trees, ores and lakes added afterwards by the game's decoration)
    blocks, _ = BetaGenerator(4817984047639240568).chunk(1, -4)
    solid = (blocks != 0) & (blocks != 9)
    top = 127 - np.argmax(solid[:, :, ::-1], axis=2)
    assert (top[:2, :8] == 86).all() and (top[:2, 8:12] == 85).all()


def test_beta_targets_get_a_blended_ring(tmp_path):
    src = SyntheticWorld(radius=1)
    src.info.level["RandomSeed"] = src.info.level["RandomSeed"].__class__(4817984047639240568)
    from worldbridge.java.numeric import JavaNumericWriter, JavaWriteOptions
    from worldbridge.model import Progress

    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    out = str(tmp_path / "beta")
    convert(hub, out, TargetSpec(family="java", java_mode="mcregion", java_version_limit="b1.7"))
    world = JavaNumericWorld(out)
    coords = set(world.chunk_coords(0))
    # 2x2 converted + a ring of at least 3 chunks (wider where the height difference is larger)
    assert coords >= {(x, z) for x in range(-4, 4) for z in range(-4, 4)}
    far = max(x for x, z in coords if z == 0)
    ring = world.read_chunk(0, far, 0)
    assert not ring.terrain_populated and world.read_chunk(0, 0, 0).terrain_populated
    # the ring's outer border is the game's own terrain, so what the game generates next continues it
    gen, _ = BetaGenerator(4817984047639240568).chunk(far, 0)
    assert (np.transpose(gen, (2, 1, 0))[:, :, 15] == np.asarray(ring.blocks[:128])[:, :, 15]).all()
    # a converted world at y = 63 meets the ring without a wall
    edge = np.asarray(world.read_chunk(0, 0, 0).blocks)
    first = np.asarray(world.read_chunk(0, 1, 0).blocks)
    ground = lambda col: int(np.nonzero(np.isin(col, [1, 2, 3, 12, 13, 24]))[0].max())  # noqa: E731
    assert abs(ground(edge[:, 8, 15]) - ground(first[:, 8, 0])) <= 2


def test_no_ring_when_blending_is_off(tmp_path):
    src = SyntheticWorld(radius=0)
    from worldbridge.java.numeric import JavaNumericWriter, JavaWriteOptions
    from worldbridge.model import Progress

    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    w.add_chunk(0, src.read_chunk(0, 0, 0))
    w.finish(src.info)
    out = str(tmp_path / "beta")
    convert(hub, out, TargetSpec(family="java", java_mode="mcregion", java_version_limit="b1.7", ring=False))
    assert len(JavaNumericWorld(out).chunk_coords(0)) == 1


def test_worlds_after_beta_are_raised_one_block_for_the_beta_sea(tmp_path):
    from worldbridge.java.numeric import JavaNumericWriter, JavaWriteOptions
    from worldbridge.model import Progress

    src = SyntheticWorld(radius=1)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    convert(hub, str(tmp_path / "beta"), TargetSpec(family="java", java_mode="mcregion",
                                                          java_version_limit="b1.7", ring=False))
    c = JavaNumericWorld(str(tmp_path / "beta")).read_chunk(0, 0, 0)
    # the synthetic ground (grass at y 63) is now at y 64, with bedrock still at the bottom
    assert (np.asarray(c.blocks)[64] == 2).all() and (np.asarray(c.blocks)[0] == 7).all()


def test_light_is_computed_not_left_at_full():
    from worldbridge.model import NumericChunk

    c = NumericChunk(0, 0, 256)
    c.blocks[:64] = 1
    c.blocks[50:53, 4:7, 4:7] = 0      # a closed cave
    c.blocks[51, 5, 5] = 50            # with a torch
    sky, blk = c.compute_sky_light(), c.compute_block_light()
    assert sky[70, 0, 0] == 15 and sky[51, 5, 4] == 0 and sky[30, 8, 8] == 0   # dark underground
    assert blk[51, 5, 5] == 14 and blk[51, 5, 4] == 13 and blk[70, 0, 0] == 0


def test_blocks_unknown_to_java_1_12_do_not_become_air():
    from amulet.api.block import Block

    from worldbridge.amulet_bridge import _install_legacy_fallback, translation_manager

    _install_legacy_fallback()
    tm = translation_manager()
    be, j12 = tm.get_version("bedrock", (1, 21, 0)), tm.get_version("java", (1, 12, 2))
    got = {n: j12.block.from_universal(be.block.to_universal(Block("minecraft", n, {}))[0])[0].base_name
           for n in ("deepslate", "tuff", "deepslate_iron_ore", "seagrass", "kelp", "mangrove_log", "glow_lichen")}
    assert got == {"deepslate": "stone", "tuff": "stone", "deepslate_iron_ore": "iron_ore", "seagrass": "water",
                   "kelp": "water", "mangrove_log": "log", "glow_lichen": "air"}


def test_mud_is_soil_in_every_older_target():
    from amulet.api.block import Block

    from worldbridge.amulet_bridge import _install_legacy_fallback, translation_manager

    _install_legacy_fallback()
    tm = translation_manager()
    src = tm.get_version("java", (26, 3, 0))
    for plat, ver, dirt in (("java", (1, 12, 2), "dirt"), ("java", (1, 16, 5), "dirt"), ("bedrock", (1, 16, 220), "dirt")):
        dst = tm.get_version(plat, ver)
        for n in ("mud", "packed_mud", "muddy_mangrove_roots"):
            got = dst.block.from_universal(src.block.to_universal(Block("minecraft", n, {}))[0])[0].base_name
            assert got == dirt, (plat, ver, n, got)
        # newer blocks never leave holes
        got = dst.block.from_universal(src.block.to_universal(Block("minecraft", "tuff_bricks", {}))[0])[0]
        assert got.base_name != "air"
        # stand-ins better than PyMCTranslate's stone and dandelions
        for n, want in (("bamboo", ("fence", "oak_fence", "bamboo")), ("bush", ("tallgrass", "grass", "short_grass"))):
            got = dst.block.from_universal(src.block.to_universal(Block("minecraft", n, {}))[0])[0].base_name
            assert got in want, (plat, ver, n, got)
