"""Java 1.14 - 1.17 targets: the 1.16 noise generator and the ring written with the "surface" status."""
import collections
import os

import numpy as np

from worldbridge import nbt
from worldbridge.convert import TargetSpec, convert
from worldbridge.java.numeric import JavaNumericWriter, JavaWriteOptions
from worldbridge.java.region import JavaRegion
from worldbridge.model import Progress
from worldbridge.terrain import policy, ring
from worldbridge.terrain.modern16 import Modern16Generator

from .helpers import SyntheticWorld

SEED = -3878429724685138167


def test_terrain_generated_by_minecraft_1_16_5():
    # chunk (-18, -4) of seed -3878429724685138167 (plains, swamp, river) as generated by Minecraft
    # 1.16.5: air, water and rock identical in every block (the caves it carved counted as rock)
    blocks, biomes, data = Modern16Generator(SEED, "1.16").chunk(-18, -4)
    assert blocks.shape == (16, 16, 256) and set(np.unique(biomes)) == {1, 6, 7}
    solid = ~np.isin(blocks, (0, 9))
    top = 255 - np.argmax(solid[:, :, ::-1], axis=2)
    assert top[:, 0].tolist() == [56, 56, 55, 55, 55, 55, 55, 55, 55, 55, 54, 54, 54, 54, 54, 54]
    assert top[0, :].tolist() == [56, 57, 57, 57, 58, 58, 58, 58, 57, 57, 57, 57, 56, 56, 56, 56]
    assert int((blocks == 9).sum()) == 1751 and int((blocks == 1).sum()) == 12486
    assert (blocks[:, :, 0] == 7).all()                                    # the bedrock floor


def test_1_14_to_1_17_targets_get_a_ring():
    for v in ((1, 13, 2), (1, 14, 4), (1, 15, 2), (1, 16, 5), (1, 17, 1)):
        assert policy.decide(TargetSpec(family="java", java_mode="amulet", version=v), True).kind == "ring"
    assert policy.decide(TargetSpec(family="java", java_mode="amulet", version=(1, 18, 2)), True).kind == "game"


def _statuses(world):
    st = collections.Counter()
    coords = {}
    for f in os.listdir(os.path.join(world, "region")):
        rx, rz = (int(v) for v in f[2:-4].split("."))
        r = JavaRegion(os.path.join(world, "region", f))
        for lx, lz in r.chunks():
            root = nbt.load(r.read(lx, lz), compressed=False).tag
            st[str(root["Level"]["Status"])] += 1
            coords[(rx * 32 + lx, rz * 32 + lz)] = root
    return st, coords


def test_the_ring_of_1_16_worlds_is_left_to_the_game_to_carve_and_decorate(tmp_path):
    src = SyntheticWorld(radius=1)
    src.info.level["RandomSeed"] = nbt.LongTag(SEED)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    # through the numeric hub (sources of old formats)
    out = str(tmp_path / "o116")
    convert(hub, out, TargetSpec(family="java", java_mode="amulet", version=(1, 16, 5)))
    st, coords = _statuses(out)
    assert st["full"] == 4 and st[ring.RING_STATUS] > 40
    # straight through Amulet (Java 1.13+ and Bedrock sources): the ring is added afterwards
    base = str(tmp_path / "base")
    convert(hub, base, TargetSpec(family="java", java_mode="amulet", version=(1, 16, 5), ring=False))
    assert _statuses(base)[0] == {"full": 4}
    out2 = str(tmp_path / "direct")
    convert(base, out2, TargetSpec(family="java", java_mode="amulet", version=(1, 16, 5)))
    st2, coords2 = _statuses(out2)
    assert st2["full"] == 4 and st2[ring.RING_STATUS] == st[ring.RING_STATUS]
    # a selection of chunks (or the chunks the game never finished, left out by themselves) keeps the ring
    from worldbridge.selection import Selection

    out3 = str(tmp_path / "direct_sel")
    convert(base, out3, TargetSpec(family="java", java_mode="amulet", version=(1, 16, 5),
                                   selection=Selection(chunks={0: {(0, 0), (-1, 0)}})))
    st3, _c3 = _statuses(out3)
    assert st3["full"] == 2 and st3[ring.RING_STATUS] > 30
    # the ring's outer edge is the game's own terrain
    from worldbridge.mapview import java_chunk_tile

    far = max(x for x, z in coords2 if z == 0)
    tile = java_chunk_tile(coords2[(far, 0)])
    gen, _b, _d = Modern16Generator(SEED, "1.16").chunk(far, 0)
    solid = gen != 0
    top = 255 - np.argmax(solid[:, :, ::-1], axis=2)
    assert (tile.height[:, 15] == top[15, :]).all()


def test_1_13_has_the_1_12_density_and_its_ring_the_base_status(tmp_path):
    from worldbridge.terrain.modern import ModernGenerator
    from worldbridge.terrain.modern16 import Modern13Generator

    # on land (no 1.13 ocean), the rock of 1.13 is the rock of 1.12, before the surface
    b13, bio, _ = Modern13Generator(SEED).chunk(19, 22)
    b12, _, _ = ModernGenerator(SEED, "1.12", caves=False).chunk(19, 22)
    rock = lambda b: ~np.isin(b, (0, 8, 9))                     # noqa: E731
    assert (rock(b13)[:, :, 5:] == rock(b12)[:, :, 5:]).all()
    assert ring.ring_status(TargetSpec(family="java", java_mode="amulet", version=(1, 13, 2))) == "base"
    src = SyntheticWorld(radius=1)
    src.info.level["RandomSeed"] = nbt.LongTag(SEED)
    hub = str(tmp_path / "hub")
    w = JavaNumericWriter(hub, JavaWriteOptions(kind="anvil"), Progress())
    for cx, cz in src.chunk_coords(0):
        w.add_chunk(0, src.read_chunk(0, cx, cz))
    w.finish(src.info)
    out = str(tmp_path / "o113")
    convert(hub, out, TargetSpec(family="java", java_mode="amulet", version=(1, 13, 2)))
    st, _coords = _statuses(out)
    assert st["postprocessed"] == 4 and st["base"] > 40              # (1.13 calls a finished chunk "postprocessed")


def test_ocean_temperatures_as_minecraft_1_16_5():
    # the 1:4 biomes of chunk (-87, -150) stored by Minecraft 1.16.5 (frozen and cold ocean): the
    # temperature noise is read as noise(x / 8, z / 8, 0)
    from worldbridge.terrain.layers17 import Stack17

    b = Stack17("1.16", SEED).biomes4(-87 * 4, -150 * 4, 4, 4)
    assert b.ravel().tolist() == [10, 46, 46, 46, 10, 10, 46, 46, 46, 46, 46, 46, 46, 46, 46, 46]
