"""Measure how seamless the terrain ring of a conversion is.

    python tools/seamcheck.py SOURCE CONVERTED [PLAYED]

SOURCE is the world that was converted (--chunks: only the chunks of that selection), CONVERTED the world WorldBridge wrote, PLAYED (optional) the
same converted world after it was opened in the game and explored: its extra chunks are the game's.

Every column is classed as "convertito" (a chunk of SOURCE), "anello" (written by WorldBridge around
it) or "gioco" (generated by the game). For each pair of neighbouring columns of the given classes the
tool reports the step in ground height (leaves, logs, plants and snow layers do not count) and the
water that would spill (a water surface next to dry ground lower than it). A seamless border has the
same steps as the terrain on either side of it.
"""
import argparse
import collections
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from worldbridge import mapview  # noqa: E402

_SOFT = ("leaves", "log", "wood", "stem", "hyphae", "sapling", "grass", "fern", "flower", "bush", "vine", "snow",
         "tulip", "orchid", "allium", "bluet", "daisy", "poppy", "dandelion", "cornflower", "lily", "rose",
         "mushroom", "cactus", "reed", "sugar_cane", "bamboo", "kelp", "seagrass", "pickle", "coral", "torch",
         "pumpkin", "melon", "cocoa", "web", "berry", "dripleaf", "azalea", "moss_carpet", "roots", "propagule")


_IS_AIR = mapview.is_air


def _soft(name: str) -> bool:
    n = name.split(":", 1)[-1].lower()
    return n != "snow_block" and n not in ("grass_block", "mushroom_stem") and any(k in n for k in _SOFT) \
        or _IS_AIR(n)


def _ground_mode():
    """Make the map's tiles report the ground: vegetation, snow layers and logs count as air."""
    mapview.is_air = _soft
    air = mapview._NUM_AIR.copy()
    for bid in (6, 17, 18, 31, 32, 37, 38, 39, 40, 50, 59, 78, 81, 83, 86, 99, 100, 103, 104, 105, 106, 111, 127,
                141, 142, 161, 162, 175):
        air[bid * 16:bid * 16 + 16] = True
    mapview._NUM_AIR = air


def columns(path):
    """{(cx, cz): (ground [z,x], water surface [z,x] or -1)} of the Overworld."""
    src = mapview.open_map(path)
    out = {}
    try:
        for cx, cz in src.chunk_coords(0):
            t = src.tile(0, cx, cz)
            if t is None:
                continue
            h = t.height.astype(np.int32)
            ground = np.where(t.depth > 0, h - t.depth, h)
            water = np.where(t.depth > 0, h, -1)
            out[(cx, cz)] = (ground, water)
    finally:
        src.close()
    return out


def grid(cols, kind_of):
    xs = [c[0] for c in cols]
    zs = [c[1] for c in cols]
    x0, z0 = min(xs), min(zs)
    shape = ((max(xs) - x0 + 1) * 16, (max(zs) - z0 + 1) * 16)
    g = np.full(shape, -9999, np.int32)
    w = np.full(shape, -1, np.int32)
    k = np.zeros(shape, np.int8)
    for (cx, cz), (ground, water) in cols.items():
        sx, sz = (cx - x0) * 16, (cz - z0) * 16
        g[sx:sx + 16, sz:sz + 16] = ground.T                 # tiles are [z, x]
        w[sx:sx + 16, sz:sz + 16] = water.T
        k[sx:sx + 16, sz:sz + 16] = kind_of((cx, cz))
    return g, w, k


KINDS = {1: "convertito", 2: "anello", 3: "gioco"}


def report(g, w, k):
    pairs = collections.defaultdict(list)
    spills = collections.Counter()
    for dx, dz in ((1, 0), (0, 1)):
        a, b = g[:g.shape[0] - dx, :g.shape[1] - dz], g[dx:, dz:]
        wa, wb = w[:g.shape[0] - dx, :g.shape[1] - dz], w[dx:, dz:]
        ka, kb = k[:g.shape[0] - dx, :g.shape[1] - dz], k[dx:, dz:]
        ok = (a > -9999) & (b > -9999) & (ka > 0) & (kb > 0)
        lo, hi = np.minimum(ka, kb), np.maximum(ka, kb)
        for i in range(1, 4):
            for j in range(i, 4):
                m = ok & (lo == i) & (hi == j)
                if m.any():
                    pairs[(i, j)].append(np.abs(a - b)[m])
                    spill = ((wa > b) & (wb < 0)) | ((wb > a) & (wa < 0))
                    spills[(i, j)] += int((spill & m).sum())
    print(f"{'coppia di colonne':26s} {'n':>8s} {'medio':>6s} {'p99':>4s} {'max':>4s} {'>=4':>7s} {'>=8':>7s} {'acqua che cola':>15s}")
    for key in sorted(pairs):
        d = np.concatenate(pairs[key])
        name = KINDS[key[0]] + (" | " + KINDS[key[1]] if key[0] != key[1] else " (dentro)")
        print(f"{name:26s} {d.size:8d} {d.mean():6.2f} {int(np.percentile(d, 99)):4d} {int(d.max()):4d} "
              f"{(d >= 4).mean() * 100:6.2f}% {(d >= 8).mean() * 100:6.2f}% {spills[key]:15d}")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source")
    ap.add_argument("converted")
    ap.add_argument("played", nargs="?")
    ap.add_argument("--chunks", help="the MCA Selector CSV of the chunks that were converted, if not all")
    a = ap.parse_args(argv)
    _ground_mode()
    source = set(mapview.open_map(a.source).chunk_coords(0))
    if a.chunks:
        from worldbridge.selection import load_csv

        source &= load_csv(a.chunks)
    converted = columns(a.converted)
    cols = columns(a.played) if a.played else converted
    kind = lambda c: 1 if c in source else 2 if c in converted else 3          # noqa: E731
    missing = [c for c in converted if c not in cols]
    print(f"chunk: {sum(kind(c) == 1 for c in cols)} convertiti, {sum(kind(c) == 2 for c in cols)} anello, "
          f"{sum(kind(c) == 3 for c in cols)} del gioco" + (f", {len(missing)} spariti" if missing else ""))
    report(*grid(cols, kind))


if __name__ == "__main__":
    main()
